### ISSUE TITLE
Roadmap for GSOC 2016 and forward

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event#34]
GSOC 2016 is about to start. And a lot of coding activity will take place on the open-event repos in the coming months. It is good to have a roadmap of broad features we intend to add to these projects. 

Tagging all parties involved on this to give their opinion - 
@leto @mariobehling @creativepsyco  @batraabhishek @mananwason @rafalkowalski @hpdang 

## Open Event Org Server

- [x] Access control (event creators, event admins, event speakers - with different editing permissions)
- [x] Support for Oauth tokens and API keys, so 3rd party app can register and use data
- [ ] Add support for voting talks
- [ ] Support for more information about the event like nearby airport/station, bus routes.

## Open Event Android App

- [x] Automated scripts to generate apk (organisers can build apk without editing/writing any code)
- [ ] Extract API data fetching code into a separate module, and be able to turn that portion into a jar/aar library
- [ ] Support for more information about the event like nearby airport/station, bus routes.
- [ ] Add support for Android Wear, to give reminders about bookmarked events
- [ ] Add support for deeklinks to open in the app (http://event.com/speaker/1) 

## Open Event Webapp
- [ ] Move to Angular2 (or possible some framework like React/Ember) - with the objective of improving performance.
- [ ] Have theming support. Not only for colors, but more components as well. 
- [ ] Possibly extract api functionality into a separate js lib
- [ ] Implement lazy loaders or paginators for speakers and sessions when lists are long
- [ ] Support for more information about the event like nearby airport/station, bus routes.

**Comment by the-dagger** [comment]
For Open Event  Android, we can do the following things too, 
1. Creating a Wear Module that notifies the user before the event is about to start and provides the directions to it. 
The notification will also allow the user to mark his attendance for the event. 
2. Enhancing the Map Activity to allow navigation to the event location and show nearby hotels and air ports. 
It will also display the sub events that are happening in the campus. 
For F droid, we can replace the navigation button with an intent to Google maps or the default browser (if the maps app isn't installed).  
If none of this is feasible, we can use a static image instead of implementing the map activity for F droid.

**Comment by championswimmer** [comment]
Deeplink support in the app would be nice too. Adding that.

**Comment by SaptakS** [comment]
**Open Event Web App**
* In Open Event Webapp, I guess we can improve social media sharing opportunities more. We could add sharing in FB, Twitter and other social networking sites with proper hastagging. 
* Also, Webapp doesn't have deeplink for every component. So, implementing that would be helpful as well.

**Open Event Orga Server**
* Add calendar features such as directly editing events from calendar itself and exporting it to google calendar, ical, etc.
* Review System for sessions.

**Comment by SilentFlame** [comment]
@championswimmer 
these three are three different Ideas under GSOC'16 for our org, am I right?

**Comment by the-dagger** [comment]
@SilentFlame Yep

**Comment by SilentFlame** [comment]
@the-dagger  Thanks. :)

**Comment by the-dagger** [comment]
@championswimmer can we also link the event live stream (if the event has one) in the app and the webapp?

**Comment by the-dagger** [comment]
For the event app, it will also be a good idea to show the recent posts from the speakers's G+/Twitter timeline in a separate tab in the speakerDetails activity.

**Comment by the-dagger** [comment]
For the wear module, I was thinking about adding the ability to navigate to the event and mark attendance for the event too.
@championswimmer

**Comment by the-dagger** [comment]
I was also thinking about adding a section in both the Android and IOS app that will show the Pictures from the event similar to the website.
The pics can be stored into a github repo and the app can get the json from that repository using the Github API by calling the endpoint "GET /users/:username/repos".
@championswimmer your thoughts?

**Comment by the-dagger** [comment]
If we are adding review section to the app, then we must also add G+ login to the app (using the G+ API) so as to uniquely identify each and every reviewer. 
In case someone is unwilling to login, then he won't be able to post a review for the event.

**Comment by championswimmer** [comment]
All GSOC 2015 roadmaps and docs are here https://github.com/fossasia/open-event/tree/master/docs/GSOC2016

Closing this now.

**Comment by mariobehling** [comment]
@championswimmer The roadmap is a good input, but some points are being discussed. Please take out the roadmap.md as it might give the impression that this is the overall plan. Let's move the specific component discussions into issues of each component. Every project can focus on its own goals. The projects can start by using data like the JSON of OpenTechSummit.

To Do: Please take out the roadmap.md therefore.

**Comment by championswimmer** [comment]
done
